[phases.setup]
nixPkgs = ["php83", "nginx", "php83Packages.composer"]

[phases.install]
cmds = ["mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx", "chmod +x start.sh"]

[phases.build]
cmds = []

[start]
cmd = "bash start.sh"

